/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author ameya
 */
public class AddrJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddrJPanel
     */
    
    Person person;
    public AddrJPanel(Person person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addrLbl = new javax.swing.JLabel();
        stateTxt = new javax.swing.JTextField();
        straddrLbl = new javax.swing.JLabel();
        zipTxt = new javax.swing.JTextField();
        cityLbl = new javax.swing.JLabel();
        stateLbl = new javax.swing.JLabel();
        zipLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        straddrTxt = new javax.swing.JTextField();
        cityTxt = new javax.swing.JTextField();

        setBackground(java.awt.SystemColor.inactiveCaption);
        setPreferredSize(new java.awt.Dimension(650, 500));
        setLayout(null);

        addrLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addrLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addrLbl.setText("Address Information");
        add(addrLbl);
        addrLbl.setBounds(10, 11, 630, 29);
        add(stateTxt);
        stateTxt.setBounds(290, 146, 190, 23);

        straddrLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        straddrLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        straddrLbl.setText("Street Address :");
        add(straddrLbl);
        straddrLbl.setBounds(149, 58, 120, 23);
        add(zipTxt);
        zipTxt.setBounds(290, 189, 190, 23);

        cityLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cityLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cityLbl.setText("City :");
        add(cityLbl);
        cityLbl.setBounds(184, 101, 88, 23);

        stateLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stateLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stateLbl.setText("State :");
        add(stateLbl);
        stateLbl.setBounds(196, 144, 76, 23);

        zipLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zipLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        zipLbl.setText("Zip :");
        add(zipLbl);
        zipLbl.setBounds(209, 187, 63, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setLabel("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(290, 230, 80, 35);

        straddrTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                straddrTxtActionPerformed(evt);
            }
        });
        add(straddrTxt);
        straddrTxt.setBounds(290, 60, 190, 23);

        cityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTxtActionPerformed(evt);
            }
        });
        add(cityTxt);
        cityTxt.setBounds(290, 103, 190, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void straddrTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_straddrTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_straddrTxtActionPerformed

    private void cityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        person.setStr_addr(straddrTxt.getText());
        person.setCity(cityTxt.getText());
        person.setState(stateTxt.getText());
        person.setZip(zipTxt.getText());
        
        JOptionPane.showMessageDialog(this, "Address information Saved.");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addrLbl;
    private javax.swing.JLabel cityLbl;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel stateLbl;
    private javax.swing.JTextField stateTxt;
    private javax.swing.JLabel straddrLbl;
    private javax.swing.JTextField straddrTxt;
    private javax.swing.JLabel zipLbl;
    private javax.swing.JTextField zipTxt;
    // End of variables declaration//GEN-END:variables
}
