/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author ameya
 */
public class LicenseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LicenseJPanel
     */
    Person person;
    public LicenseJPanel(Person person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkBtn = new javax.swing.JButton();
        expdtTxt = new javax.swing.JTextField();
        lncsLbl = new javax.swing.JLabel();
        bldtypeTxt = new javax.swing.JTextField();
        lncsTxt = new javax.swing.JTextField();
        issuedtLbl = new javax.swing.JLabel();
        issuedtTxt = new javax.swing.JTextField();
        picTxt = new javax.swing.JTextField();
        expdtLbl = new javax.swing.JLabel();
        picLbl = new javax.swing.JLabel();
        lcnsLbl = new javax.swing.JLabel();
        bldtypeLbl = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.inactiveCaption);
        setPreferredSize(new java.awt.Dimension(650, 500));
        setLayout(null);

        chkBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkBtn.setLabel("Save");
        chkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBtnActionPerformed(evt);
            }
        });
        add(chkBtn);
        chkBtn.setBounds(288, 275, 80, 35);

        expdtTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expdtTxtActionPerformed(evt);
            }
        });
        add(expdtTxt);
        expdtTxt.setBounds(288, 146, 190, 23);

        lncsLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lncsLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lncsLbl.setText("License Number :");
        add(lncsLbl);
        lncsLbl.setBounds(146, 58, 120, 23);
        add(bldtypeTxt);
        bldtypeTxt.setBounds(288, 189, 190, 23);

        lncsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lncsTxtActionPerformed(evt);
            }
        });
        add(lncsTxt);
        lncsTxt.setBounds(288, 60, 190, 23);

        issuedtLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        issuedtLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        issuedtLbl.setText("Date of Issue :");
        add(issuedtLbl);
        issuedtLbl.setBounds(155, 101, 110, 23);

        issuedtTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedtTxtActionPerformed(evt);
            }
        });
        add(issuedtTxt);
        issuedtTxt.setBounds(288, 103, 190, 23);
        add(picTxt);
        picTxt.setBounds(288, 232, 190, 23);

        expdtLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        expdtLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        expdtLbl.setText("Date of Expirate :");
        add(expdtLbl);
        expdtLbl.setBounds(147, 144, 120, 23);

        picLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        picLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        picLbl.setText("Picture :");
        add(picLbl);
        picLbl.setBounds(150, 230, 120, 23);

        lcnsLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lcnsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcnsLbl.setText("Driver's License Information");
        add(lcnsLbl);
        lcnsLbl.setBounds(10, 11, 630, 29);

        bldtypeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bldtypeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bldtypeLbl.setText("Blood Type :");
        add(bldtypeLbl);
        bldtypeLbl.setBounds(128, 187, 142, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void expdtTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expdtTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expdtTxtActionPerformed

    private void lncsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lncsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lncsTxtActionPerformed

    private void issuedtTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedtTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issuedtTxtActionPerformed

    private void chkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBtnActionPerformed
        // TODO add your handling code here:
        person.setLcnsnum(lncsTxt.getText());
        person.setIss_dt(issuedtTxt.getText());
        person.setBld_type(bldtypeTxt.getText());
        person.setExp_dt(expdtTxt.getText());
        person.setPicture(picTxt.getText());
        
        JOptionPane.showMessageDialog(this, "License Information Saved.");
        
    }//GEN-LAST:event_chkBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bldtypeLbl;
    private javax.swing.JTextField bldtypeTxt;
    private javax.swing.JButton chkBtn;
    private javax.swing.JLabel expdtLbl;
    private javax.swing.JTextField expdtTxt;
    private javax.swing.JLabel issuedtLbl;
    private javax.swing.JTextField issuedtTxt;
    private javax.swing.JLabel lcnsLbl;
    private javax.swing.JLabel lncsLbl;
    private javax.swing.JTextField lncsTxt;
    private javax.swing.JLabel picLbl;
    private javax.swing.JTextField picTxt;
    // End of variables declaration//GEN-END:variables
}
