/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.Person;

/**
 *
 * @author ameya
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    Person person;
    public MainJFrame() {
        initComponents();
        person = new Person();
        this.setSize(1050, 550);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        displayArea = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        demoBtn = new javax.swing.JButton();
        addrBtn = new javax.swing.JButton();
        svngBtn = new javax.swing.JButton();
        chkngBtn = new javax.swing.JButton();
        lcnsBtn = new javax.swing.JButton();
        mdclBtn = new javax.swing.JButton();
        rprtBtn = new javax.swing.JButton();
        menuLbl = new javax.swing.JLabel();
        demoLbl = new javax.swing.JLabel();
        demoViewBtn = new javax.swing.JButton();
        addrLbl = new javax.swing.JLabel();
        addrViewBtn = new javax.swing.JButton();
        svngLbl = new javax.swing.JLabel();
        svngViewBtn = new javax.swing.JButton();
        chkngLbl = new javax.swing.JLabel();
        chkngViewBtn = new javax.swing.JButton();
        lcnsLbl = new javax.swing.JLabel();
        lcnsViewBtn = new javax.swing.JButton();
        mdcLbl = new javax.swing.JLabel();
        mdcViewBtn = new javax.swing.JButton();
        rprtLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1000, 500));
        setSize(new java.awt.Dimension(750, 350));

        splitPane.setDividerLocation(200);
        splitPane.setLastDividerLocation(200);
        splitPane.setMinimumSize(new java.awt.Dimension(200, 500));
        splitPane.setPreferredSize(new java.awt.Dimension(850, 500));

        displayArea.setBackground(java.awt.SystemColor.inactiveCaption);
        displayArea.setPreferredSize(new java.awt.Dimension(650, 500));
        displayArea.setLayout(null);
        splitPane.setRightComponent(displayArea);

        controlPanel.setBackground(java.awt.SystemColor.inactiveCaption);
        controlPanel.setPreferredSize(new java.awt.Dimension(200, 500));
        controlPanel.setLayout(null);

        demoBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        demoBtn.setText("Create");
        demoBtn.setPreferredSize(new java.awt.Dimension(80, 23));
        demoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoBtnActionPerformed(evt);
            }
        });
        controlPanel.add(demoBtn);
        demoBtn.setBounds(17, 84, 80, 23);

        addrBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addrBtn.setText("Create");
        addrBtn.setPreferredSize(new java.awt.Dimension(80, 23));
        addrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrBtnActionPerformed(evt);
            }
        });
        controlPanel.add(addrBtn);
        addrBtn.setBounds(17, 144, 80, 23);

        svngBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        svngBtn.setText("Create");
        svngBtn.setPreferredSize(new java.awt.Dimension(80, 23));
        svngBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svngBtnActionPerformed(evt);
            }
        });
        controlPanel.add(svngBtn);
        svngBtn.setBounds(17, 199, 80, 23);

        chkngBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkngBtn.setText("Create");
        chkngBtn.setPreferredSize(new java.awt.Dimension(80, 23));
        chkngBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkngBtnActionPerformed(evt);
            }
        });
        controlPanel.add(chkngBtn);
        chkngBtn.setBounds(17, 259, 80, 23);

        lcnsBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lcnsBtn.setText("Create");
        lcnsBtn.setPreferredSize(new java.awt.Dimension(65, 23));
        lcnsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcnsBtnActionPerformed(evt);
            }
        });
        controlPanel.add(lcnsBtn);
        lcnsBtn.setBounds(17, 319, 80, 23);

        mdclBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mdclBtn.setText("Create");
        mdclBtn.setPreferredSize(new java.awt.Dimension(65, 23));
        mdclBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdclBtnActionPerformed(evt);
            }
        });
        controlPanel.add(mdclBtn);
        mdclBtn.setBounds(17, 374, 80, 23);

        rprtBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rprtBtn.setText("Report");
        rprtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rprtBtnActionPerformed(evt);
            }
        });
        controlPanel.add(rprtBtn);
        rprtBtn.setBounds(71, 429, 67, 23);

        menuLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        menuLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLbl.setText("MENU");
        controlPanel.add(menuLbl);
        menuLbl.setBounds(10, 11, 167, 41);

        demoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        demoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        demoLbl.setText(" Demographic Information");
        controlPanel.add(demoLbl);
        demoLbl.setBounds(10, 58, 167, 15);

        demoViewBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        demoViewBtn.setText("View");
        demoViewBtn.setPreferredSize(new java.awt.Dimension(80, 23));
        demoViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoViewBtnActionPerformed(evt);
            }
        });
        controlPanel.add(demoViewBtn);
        demoViewBtn.setBounds(103, 84, 80, 23);

        addrLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addrLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addrLbl.setText("Address Information");
        controlPanel.add(addrLbl);
        addrLbl.setBounds(10, 118, 180, 15);

        addrViewBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addrViewBtn.setText("View");
        addrViewBtn.setPreferredSize(new java.awt.Dimension(80, 23));
        addrViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrViewBtnActionPerformed(evt);
            }
        });
        controlPanel.add(addrViewBtn);
        addrViewBtn.setBounds(103, 144, 80, 23);

        svngLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        svngLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        svngLbl.setText("Savings Account Information");
        controlPanel.add(svngLbl);
        svngLbl.setBounds(27, 178, 150, 15);

        svngViewBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        svngViewBtn.setText("View");
        svngViewBtn.setPreferredSize(new java.awt.Dimension(80, 23));
        svngViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svngViewBtnActionPerformed(evt);
            }
        });
        controlPanel.add(svngViewBtn);
        svngViewBtn.setBounds(103, 199, 80, 23);

        chkngLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkngLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chkngLbl.setText("Checking Account Information");
        controlPanel.add(chkngLbl);
        chkngLbl.setBounds(10, 233, 180, 15);

        chkngViewBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkngViewBtn.setText("View");
        chkngViewBtn.setPreferredSize(new java.awt.Dimension(80, 23));
        chkngViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkngViewBtnActionPerformed(evt);
            }
        });
        controlPanel.add(chkngViewBtn);
        chkngViewBtn.setBounds(103, 259, 80, 23);

        lcnsLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lcnsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcnsLbl.setText("Driver's License Information");
        controlPanel.add(lcnsLbl);
        lcnsLbl.setBounds(10, 293, 180, 15);

        lcnsViewBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lcnsViewBtn.setText("View");
        lcnsViewBtn.setPreferredSize(new java.awt.Dimension(80, 23));
        lcnsViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcnsViewBtnActionPerformed(evt);
            }
        });
        controlPanel.add(lcnsViewBtn);
        lcnsViewBtn.setBounds(103, 319, 80, 23);

        mdcLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mdcLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mdcLbl.setText("Medical Record Information");
        controlPanel.add(mdcLbl);
        mdcLbl.setBounds(10, 348, 180, 15);

        mdcViewBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mdcViewBtn.setText("View");
        mdcViewBtn.setPreferredSize(new java.awt.Dimension(80, 23));
        mdcViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdcViewBtnActionPerformed(evt);
            }
        });
        controlPanel.add(mdcViewBtn);
        mdcViewBtn.setBounds(103, 374, 80, 23);

        rprtLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rprtLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rprtLbl.setText("Report");
        controlPanel.add(rprtLbl);
        rprtLbl.setBounds(10, 408, 180, 15);

        splitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void demoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoBtnActionPerformed
        // TODO add your handling code here:
        DemoJPanel demo = new DemoJPanel(person);
        splitPane.setRightComponent(demo); 
    }//GEN-LAST:event_demoBtnActionPerformed

    private void addrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrBtnActionPerformed
        // TODO add your handling code here:
        AddrJPanel addr = new AddrJPanel(person);
        splitPane.setRightComponent(addr); 
        
    }//GEN-LAST:event_addrBtnActionPerformed

    private void svngBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svngBtnActionPerformed
        // TODO add your handling code here:
        SavingsJPanel svng = new SavingsJPanel(person);
        splitPane.setRightComponent(svng);
    }//GEN-LAST:event_svngBtnActionPerformed

    private void chkngBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkngBtnActionPerformed
        // TODO add your handling code here:
        CheckingJPanel chk = new CheckingJPanel(person);
        splitPane.setRightComponent(chk);
    }//GEN-LAST:event_chkngBtnActionPerformed

    private void lcnsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcnsBtnActionPerformed
        // TODO add your handling code here:
        LicenseJPanel lcns = new LicenseJPanel(person);
        splitPane.setRightComponent(lcns);
    }//GEN-LAST:event_lcnsBtnActionPerformed

    private void mdclBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdclBtnActionPerformed
        // TODO add your handling code here:
        MedJPanel med = new MedJPanel(person);
        splitPane.setRightComponent(med);
    }//GEN-LAST:event_mdclBtnActionPerformed

    private void rprtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rprtBtnActionPerformed
        // TODO add your handling code here:
        ReportJPanel rprt = new ReportJPanel(person);
        splitPane.setRightComponent(rprt);
        
    }//GEN-LAST:event_rprtBtnActionPerformed

    private void demoViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoViewBtnActionPerformed
        // TODO add your handling code here:
        ViewDemoJPanel viewdemo = new ViewDemoJPanel(person);
        splitPane.setRightComponent(viewdemo); 
        
    }//GEN-LAST:event_demoViewBtnActionPerformed

    private void addrViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrViewBtnActionPerformed
        // TODO add your handling code here:
        ViewAddrJPanel viewaddr = new ViewAddrJPanel(person);
        splitPane.setRightComponent(viewaddr);
    }//GEN-LAST:event_addrViewBtnActionPerformed

    private void svngViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svngViewBtnActionPerformed
        // TODO add your handling code here:
        ViewSavingsJPanel viewsvng = new ViewSavingsJPanel(person);
        splitPane.setRightComponent(viewsvng);
        
    }//GEN-LAST:event_svngViewBtnActionPerformed

    private void chkngViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkngViewBtnActionPerformed
        // TODO add your handling code here:
        ViewCheckingJPanel viewchk = new ViewCheckingJPanel(person);
        splitPane.setRightComponent(viewchk);
        
    }//GEN-LAST:event_chkngViewBtnActionPerformed

    private void lcnsViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcnsViewBtnActionPerformed
        // TODO add your handling code here:
        ViewLicenseJPanel viewlcns = new ViewLicenseJPanel(person);
        splitPane.setRightComponent(viewlcns);
    }//GEN-LAST:event_lcnsViewBtnActionPerformed

    private void mdcViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdcViewBtnActionPerformed
        // TODO add your handling code here:
        ViewMedJPanel viewmed = new ViewMedJPanel(person);
        splitPane.setRightComponent(viewmed);
    }//GEN-LAST:event_mdcViewBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                              
                new MainJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addrBtn;
    private javax.swing.JLabel addrLbl;
    private javax.swing.JButton addrViewBtn;
    private javax.swing.JButton chkngBtn;
    private javax.swing.JLabel chkngLbl;
    private javax.swing.JButton chkngViewBtn;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton demoBtn;
    private javax.swing.JLabel demoLbl;
    private javax.swing.JButton demoViewBtn;
    private javax.swing.JPanel displayArea;
    private javax.swing.JButton lcnsBtn;
    private javax.swing.JLabel lcnsLbl;
    private javax.swing.JButton lcnsViewBtn;
    private javax.swing.JLabel mdcLbl;
    private javax.swing.JButton mdcViewBtn;
    private javax.swing.JButton mdclBtn;
    private javax.swing.JLabel menuLbl;
    private javax.swing.JButton rprtBtn;
    private javax.swing.JLabel rprtLbl;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JButton svngBtn;
    private javax.swing.JLabel svngLbl;
    private javax.swing.JButton svngViewBtn;
    // End of variables declaration//GEN-END:variables
}
