/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.Person;

/**
 *
 * @author ameya
 */
public class ReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportJPanel
     */
    
    Person person;
    public ReportJPanel(Person person) {
        initComponents();
        
        this.person = person;
        displayPerson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rprtLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lnameLbl = new javax.swing.JLabel();
        ssnTxt = new javax.swing.JTextField();
        dobLbl = new javax.swing.JLabel();
        dobTxt = new javax.swing.JTextField();
        ageLbl = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        hgtLbl = new javax.swing.JLabel();
        wgtLbl = new javax.swing.JLabel();
        ssnLbl = new javax.swing.JLabel();
        fnameTxt = new javax.swing.JTextField();
        lnameTxt = new javax.swing.JTextField();
        stateLbl = new javax.swing.JLabel();
        zipLbl = new javax.swing.JLabel();
        stateTxt = new javax.swing.JTextField();
        straddrLbl = new javax.swing.JLabel();
        zipTxt = new javax.swing.JTextField();
        straddrTxt = new javax.swing.JTextField();
        cityLbl = new javax.swing.JLabel();
        cityTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        hgtTxt = new javax.swing.JTextField();
        fnameLbl = new javax.swing.JLabel();
        wgtTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        svngbnknameTxt = new javax.swing.JTextField();
        rtngLbl = new javax.swing.JLabel();
        svngrtngTxt = new javax.swing.JTextField();
        svngacctypeTxt = new javax.swing.JTextField();
        svngaccLbl = new javax.swing.JLabel();
        svngacctypeLbl = new javax.swing.JLabel();
        svngaccbalLbl = new javax.swing.JLabel();
        chkaccTxt = new javax.swing.JTextField();
        chkaccbalTxt = new javax.swing.JTextField();
        chkacctypeTxt = new javax.swing.JTextField();
        chkbnknameLbl = new javax.swing.JLabel();
        chkaccLbl = new javax.swing.JLabel();
        chkbnknameTxt = new javax.swing.JTextField();
        chkacctypeLbl = new javax.swing.JLabel();
        chkrtngLbl = new javax.swing.JLabel();
        chkaccbalLbl = new javax.swing.JLabel();
        chkrtngTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        svngTxt = new javax.swing.JTextField();
        bnknameLbl = new javax.swing.JLabel();
        svngaccbalTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lncsLbl = new javax.swing.JLabel();
        alrg3Txt = new javax.swing.JTextField();
        alrg3 = new javax.swing.JLabel();
        expdtLbl = new javax.swing.JLabel();
        picLbl = new javax.swing.JLabel();
        expdtTxt = new javax.swing.JTextField();
        alrg1Lbl = new javax.swing.JLabel();
        alrg2Txt = new javax.swing.JTextField();
        alrg1Txt = new javax.swing.JTextField();
        picTxt = new javax.swing.JTextField();
        medrecTxt = new javax.swing.JTextField();
        issuedtTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bldtypeTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        issuedtLbl = new javax.swing.JLabel();
        medrecLbl = new javax.swing.JLabel();
        alrg2Lbl = new javax.swing.JLabel();
        bldtypeLbl = new javax.swing.JLabel();
        lncsTxt = new javax.swing.JTextField();

        setBackground(java.awt.SystemColor.inactiveCaption);
        setBorder(javax.swing.BorderFactory.createCompoundBorder());
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(null);

        rprtLbl.setBackground(java.awt.SystemColor.activeCaption);
        rprtLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rprtLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rprtLbl.setText("REPORT");
        rprtLbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(rprtLbl);
        rprtLbl.setBounds(277, 11, 315, 28);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 450));
        jPanel1.setLayout(null);

        lnameLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lnameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lnameLbl.setText("Las Name :");
        jPanel1.add(lnameLbl);
        lnameLbl.setBounds(13, 81, 106, 23);

        ssnTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ssnTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel1.add(ssnTxt);
        ssnTxt.setBounds(137, 251, 100, 23);

        dobLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dobLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dobLbl.setText("Date of birth :");
        jPanel1.add(dobLbl);
        dobLbl.setBounds(13, 115, 110, 23);

        dobTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dobTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel1.add(dobTxt);
        dobTxt.setBounds(137, 115, 100, 23);

        ageLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ageLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ageLbl.setText("Age :");
        jPanel1.add(ageLbl);
        ageLbl.setBounds(13, 149, 106, 23);

        ageTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ageTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel1.add(ageTxt);
        ageTxt.setBounds(137, 149, 100, 23);

        hgtLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hgtLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hgtLbl.setText("Height :");
        jPanel1.add(hgtLbl);
        hgtLbl.setBounds(13, 183, 106, 23);

        wgtLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        wgtLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        wgtLbl.setText("Weight :");
        jPanel1.add(wgtLbl);
        wgtLbl.setBounds(13, 217, 100, 23);

        ssnLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ssnLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ssnLbl.setText("SSN :");
        jPanel1.add(ssnLbl);
        ssnLbl.setBounds(13, 251, 100, 23);

        fnameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fnameTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        fnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(fnameTxt);
        fnameTxt.setBounds(137, 47, 100, 23);

        lnameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lnameTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        lnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(lnameTxt);
        lnameTxt.setBounds(137, 82, 100, 21);

        stateLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stateLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stateLbl.setText("State :");
        jPanel1.add(stateLbl);
        stateLbl.setBounds(13, 371, 105, 23);

        zipLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        zipLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        zipLbl.setText("Zip :");
        jPanel1.add(zipLbl);
        zipLbl.setBounds(13, 405, 105, 23);

        stateTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stateTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel1.add(stateTxt);
        stateTxt.setBounds(136, 371, 101, 23);

        straddrLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        straddrLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        straddrLbl.setText("Street Address :");
        jPanel1.add(straddrLbl);
        straddrLbl.setBounds(13, 313, 105, 23);

        zipTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        zipTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel1.add(zipTxt);
        zipTxt.setBounds(136, 405, 101, 23);

        straddrTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        straddrTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        straddrTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                straddrTxtActionPerformed(evt);
            }
        });
        jPanel1.add(straddrTxt);
        straddrTxt.setBounds(136, 313, 101, 23);

        cityLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cityLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cityLbl.setText("City :");
        jPanel1.add(cityLbl);
        cityLbl.setBounds(13, 342, 105, 23);

        cityTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cityTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        cityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTxtActionPerformed(evt);
            }
        });
        jPanel1.add(cityTxt);
        cityTxt.setBounds(136, 342, 101, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Demographic");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(13, 14, 224, 27);

        hgtTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hgtTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel1.add(hgtTxt);
        hgtTxt.setBounds(137, 183, 100, 23);

        fnameLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fnameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fnameLbl.setText("First Name :");
        jPanel1.add(fnameLbl);
        fnameLbl.setBounds(13, 47, 108, 23);

        wgtTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        wgtTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel1.add(wgtTxt);
        wgtTxt.setBounds(137, 217, 100, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Address");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(13, 280, 224, 27);

        add(jPanel1);
        jPanel1.setBounds(10, 45, 250, 452);

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 450));
        jPanel2.setLayout(null);

        svngbnknameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        svngbnknameTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        svngbnknameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svngbnknameTxtActionPerformed(evt);
            }
        });
        jPanel2.add(svngbnknameTxt);
        svngbnknameTxt.setBounds(115, 47, 100, 23);

        rtngLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rtngLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rtngLbl.setText("Routing Number :");
        jPanel2.add(rtngLbl);
        rtngLbl.setBounds(13, 81, 97, 23);

        svngrtngTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        svngrtngTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        svngrtngTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svngrtngTxtActionPerformed(evt);
            }
        });
        jPanel2.add(svngrtngTxt);
        svngrtngTxt.setBounds(117, 81, 100, 23);

        svngacctypeTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        svngacctypeTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        svngacctypeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svngacctypeTxtActionPerformed(evt);
            }
        });
        jPanel2.add(svngacctypeTxt);
        svngacctypeTxt.setBounds(119, 183, 100, 23);

        svngaccLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        svngaccLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        svngaccLbl.setText("Savings AC# :");
        jPanel2.add(svngaccLbl);
        svngaccLbl.setBounds(13, 115, 92, 23);

        svngacctypeLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        svngacctypeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        svngacctypeLbl.setText("Account Type :");
        jPanel2.add(svngacctypeLbl);
        svngacctypeLbl.setBounds(13, 183, 94, 23);

        svngaccbalLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        svngaccbalLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        svngaccbalLbl.setText("Account Balance :");
        jPanel2.add(svngaccbalLbl);
        svngaccbalLbl.setBounds(13, 149, 99, 23);

        chkaccTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkaccTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        chkaccTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkaccTxtActionPerformed(evt);
            }
        });
        jPanel2.add(chkaccTxt);
        chkaccTxt.setBounds(137, 341, 100, 23);

        chkaccbalTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkaccbalTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        chkaccbalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkaccbalTxtActionPerformed(evt);
            }
        });
        jPanel2.add(chkaccbalTxt);
        chkaccbalTxt.setBounds(137, 370, 100, 23);

        chkacctypeTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkacctypeTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel2.add(chkacctypeTxt);
        chkacctypeTxt.setBounds(137, 404, 100, 23);

        chkbnknameLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkbnknameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chkbnknameLbl.setText("Bank Name :");
        jPanel2.add(chkbnknameLbl);
        chkbnknameLbl.setBounds(13, 283, 108, 23);

        chkaccLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkaccLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chkaccLbl.setText("Checking AC# :");
        jPanel2.add(chkaccLbl);
        chkaccLbl.setBounds(15, 341, 106, 23);

        chkbnknameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkbnknameTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        chkbnknameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbnknameTxtActionPerformed(evt);
            }
        });
        jPanel2.add(chkbnknameTxt);
        chkbnknameTxt.setBounds(137, 283, 100, 23);

        chkacctypeLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkacctypeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chkacctypeLbl.setText("Account Type :");
        jPanel2.add(chkacctypeLbl);
        chkacctypeLbl.setBounds(13, 404, 108, 23);

        chkrtngLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkrtngLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chkrtngLbl.setText("Routing Number :");
        jPanel2.add(chkrtngLbl);
        chkrtngLbl.setBounds(15, 312, 106, 23);

        chkaccbalLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkaccbalLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chkaccbalLbl.setText("Account Balance :");
        jPanel2.add(chkaccbalLbl);
        chkaccbalLbl.setBounds(19, 370, 108, 23);

        chkrtngTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkrtngTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        chkrtngTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkrtngTxtActionPerformed(evt);
            }
        });
        jPanel2.add(chkrtngTxt);
        chkrtngTxt.setBounds(137, 312, 100, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Savings Account");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(13, 14, 224, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Checking Account");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(13, 249, 224, 23);

        svngTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        svngTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel2.add(svngTxt);
        svngTxt.setBounds(117, 115, 100, 23);

        bnknameLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bnknameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bnknameLbl.setText("Bank Name :");
        jPanel2.add(bnknameLbl);
        bnknameLbl.setBounds(13, 47, 92, 23);

        svngaccbalTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        svngaccbalTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel2.add(svngaccbalTxt);
        svngaccbalTxt.setBounds(119, 149, 100, 23);

        add(jPanel2);
        jPanel2.setBounds(278, 45, 250, 452);

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 450));
        jPanel3.setLayout(null);

        lncsLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lncsLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lncsLbl.setText("License Number :");
        jPanel3.add(lncsLbl);
        lncsLbl.setBounds(13, 47, 95, 23);

        alrg3Txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        alrg3Txt.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel3.add(alrg3Txt);
        alrg3Txt.setBounds(123, 374, 100, 23);

        alrg3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        alrg3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        alrg3.setText("Allergy 3 :");
        jPanel3.add(alrg3);
        alrg3.setBounds(38, 374, 67, 23);

        expdtLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        expdtLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        expdtLbl.setText("Date of Expirate :");
        jPanel3.add(expdtLbl);
        expdtLbl.setBounds(13, 81, 97, 23);

        picLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        picLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        picLbl.setText("Picture :");
        jPanel3.add(picLbl);
        picLbl.setBounds(13, 183, 93, 23);

        expdtTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        expdtTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        expdtTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expdtTxtActionPerformed(evt);
            }
        });
        jPanel3.add(expdtTxt);
        expdtTxt.setBounds(116, 81, 100, 23);

        alrg1Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        alrg1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        alrg1Lbl.setText("Allergy 1 :");
        jPanel3.add(alrg1Lbl);
        alrg1Lbl.setBounds(19, 316, 86, 23);

        alrg2Txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        alrg2Txt.setPreferredSize(new java.awt.Dimension(100, 21));
        alrg2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alrg2TxtActionPerformed(evt);
            }
        });
        jPanel3.add(alrg2Txt);
        alrg2Txt.setBounds(123, 345, 100, 23);

        alrg1Txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        alrg1Txt.setPreferredSize(new java.awt.Dimension(100, 21));
        alrg1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alrg1TxtActionPerformed(evt);
            }
        });
        jPanel3.add(alrg1Txt);
        alrg1Txt.setBounds(123, 316, 100, 23);

        picTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        picTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel3.add(picTxt);
        picTxt.setBounds(116, 183, 100, 23);

        medrecTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        medrecTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        medrecTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medrecTxtActionPerformed(evt);
            }
        });
        jPanel3.add(medrecTxt);
        medrecTxt.setBounds(123, 287, 100, 23);

        issuedtTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        issuedtTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        issuedtTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedtTxtActionPerformed(evt);
            }
        });
        jPanel3.add(issuedtTxt);
        issuedtTxt.setBounds(116, 115, 100, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("License");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel4);
        jLabel4.setBounds(13, 14, 212, 27);

        bldtypeTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bldtypeTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        bldtypeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bldtypeTxtActionPerformed(evt);
            }
        });
        jPanel3.add(bldtypeTxt);
        bldtypeTxt.setBounds(116, 149, 100, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Medical Record");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel5);
        jLabel5.setBounds(13, 249, 212, 27);

        issuedtLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        issuedtLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        issuedtLbl.setText("Date of Issue :");
        jPanel3.add(issuedtLbl);
        issuedtLbl.setBounds(13, 115, 93, 23);

        medrecLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        medrecLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medrecLbl.setText("Medical Rcrd No. :");
        jPanel3.add(medrecLbl);
        medrecLbl.setBounds(23, 287, 96, 23);

        alrg2Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        alrg2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        alrg2Lbl.setText("Allergy 2 :");
        jPanel3.add(alrg2Lbl);
        alrg2Lbl.setBounds(38, 345, 67, 23);

        bldtypeLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bldtypeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bldtypeLbl.setText("Blood Type :");
        jPanel3.add(bldtypeLbl);
        bldtypeLbl.setBounds(13, 149, 93, 23);

        lncsTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lncsTxt.setPreferredSize(new java.awt.Dimension(100, 21));
        lncsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lncsTxtActionPerformed(evt);
            }
        });
        jPanel3.add(lncsTxt);
        lncsTxt.setBounds(114, 47, 102, 23);

        add(jPanel3);
        jPanel3.setBounds(546, 45, 238, 452);
    }// </editor-fold>//GEN-END:initComponents

    private void fnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameTxtActionPerformed

    private void lnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameTxtActionPerformed

    private void straddrTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_straddrTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_straddrTxtActionPerformed

    private void cityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTxtActionPerformed

    private void svngbnknameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svngbnknameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_svngbnknameTxtActionPerformed

    private void svngrtngTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svngrtngTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_svngrtngTxtActionPerformed

    private void svngacctypeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svngacctypeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_svngacctypeTxtActionPerformed

    private void chkaccTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkaccTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkaccTxtActionPerformed

    private void chkbnknameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbnknameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkbnknameTxtActionPerformed

    private void chkrtngTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkrtngTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkrtngTxtActionPerformed

    private void chkaccbalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkaccbalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkaccbalTxtActionPerformed

    private void lncsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lncsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lncsTxtActionPerformed

    private void bldtypeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bldtypeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bldtypeTxtActionPerformed

    private void issuedtTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedtTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issuedtTxtActionPerformed

    private void medrecTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medrecTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medrecTxtActionPerformed

    private void alrg1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alrg1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alrg1TxtActionPerformed

    private void alrg2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alrg2TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alrg2TxtActionPerformed

    private void expdtTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expdtTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expdtTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLbl;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JLabel alrg1Lbl;
    private javax.swing.JTextField alrg1Txt;
    private javax.swing.JLabel alrg2Lbl;
    private javax.swing.JTextField alrg2Txt;
    private javax.swing.JLabel alrg3;
    private javax.swing.JTextField alrg3Txt;
    private javax.swing.JLabel bldtypeLbl;
    private javax.swing.JTextField bldtypeTxt;
    private javax.swing.JLabel bnknameLbl;
    private javax.swing.JLabel chkaccLbl;
    private javax.swing.JTextField chkaccTxt;
    private javax.swing.JLabel chkaccbalLbl;
    private javax.swing.JTextField chkaccbalTxt;
    private javax.swing.JLabel chkacctypeLbl;
    private javax.swing.JTextField chkacctypeTxt;
    private javax.swing.JLabel chkbnknameLbl;
    private javax.swing.JTextField chkbnknameTxt;
    private javax.swing.JLabel chkrtngLbl;
    private javax.swing.JTextField chkrtngTxt;
    private javax.swing.JLabel cityLbl;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JLabel dobLbl;
    private javax.swing.JTextField dobTxt;
    private javax.swing.JLabel expdtLbl;
    private javax.swing.JTextField expdtTxt;
    private javax.swing.JLabel fnameLbl;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JLabel hgtLbl;
    private javax.swing.JTextField hgtTxt;
    private javax.swing.JLabel issuedtLbl;
    private javax.swing.JTextField issuedtTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lnameLbl;
    private javax.swing.JTextField lnameTxt;
    private javax.swing.JLabel lncsLbl;
    private javax.swing.JTextField lncsTxt;
    private javax.swing.JLabel medrecLbl;
    private javax.swing.JTextField medrecTxt;
    private javax.swing.JLabel picLbl;
    private javax.swing.JTextField picTxt;
    private javax.swing.JLabel rprtLbl;
    private javax.swing.JLabel rtngLbl;
    private javax.swing.JLabel ssnLbl;
    private javax.swing.JTextField ssnTxt;
    private javax.swing.JLabel stateLbl;
    private javax.swing.JTextField stateTxt;
    private javax.swing.JLabel straddrLbl;
    private javax.swing.JTextField straddrTxt;
    private javax.swing.JTextField svngTxt;
    private javax.swing.JLabel svngaccLbl;
    private javax.swing.JLabel svngaccbalLbl;
    private javax.swing.JTextField svngaccbalTxt;
    private javax.swing.JLabel svngacctypeLbl;
    private javax.swing.JTextField svngacctypeTxt;
    private javax.swing.JTextField svngbnknameTxt;
    private javax.swing.JTextField svngrtngTxt;
    private javax.swing.JLabel wgtLbl;
    private javax.swing.JTextField wgtTxt;
    private javax.swing.JLabel zipLbl;
    private javax.swing.JTextField zipTxt;
    // End of variables declaration//GEN-END:variables

    private void displayPerson() {
        
        fnameTxt.setText(person.getF_name());
        lnameTxt.setText(person.getL_name());
        dobTxt.setText(person.getDob());
        ageTxt.setText(person.getAge());
        hgtTxt.setText(person.getHgt());
        wgtTxt.setText(person.getWgt());
        ssnTxt.setText(person.getSsn());
        
        straddrTxt.setText(person.getStr_addr());
        cityTxt.setText(person.getCity());
        stateTxt.setText(person.getState());
        zipTxt.setText(person.getZip());
        
        svngbnknameTxt.setText(person.getSave_name());
        svngrtngTxt.setText(person.getSave__rnum());
        svngTxt.setText(person.getSave__accnum());
        svngaccbalTxt.setText(person.getSave__accbal());
        svngacctypeTxt.setText(person.getSave__acctype());
        
        chkbnknameTxt.setText(person.getChk_name());
        chkrtngTxt.setText(person.getChk__rnum());
        chkaccTxt.setText(person.getChk__accnum());
        chkaccbalTxt.setText(person.getChk__accbal());
        chkacctypeTxt.setText(person.getChk__acctype());
        
        lncsTxt.setText(person.getLcnsnum());
        issuedtTxt.setText(person.getIss_dt());
        expdtTxt.setText(person.getExp_dt());
        bldtypeTxt.setText(person.getBld_type());
        picTxt.setText(person.getPicture());
        
        medrecTxt.setText(person.getM_rcrdnum());
        alrg1Txt.setText(person.getAlrg_1());
        alrg2Txt.setText(person.getAlrg_2());
        alrg3Txt.setText(person.getAlrg_3());
        
        
        
        
        
        
        
        
        
    }
}

