/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.Person;

/**
 *
 * @author ameya
 */
public class ViewMedJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewMedJPanel
     */
    Person person;
    public ViewMedJPanel(Person person) {
        initComponents();
        this.setSize(2000, 2000);
        this.person = person;
        displayperson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alrg3Txt = new javax.swing.JTextField();
        medrecTxt = new javax.swing.JTextField();
        alrg1Lbl = new javax.swing.JLabel();
        alrg1Txt = new javax.swing.JTextField();
        alrg2Lbl = new javax.swing.JLabel();
        medLbl = new javax.swing.JLabel();
        alrg3 = new javax.swing.JLabel();
        alrg2Txt = new javax.swing.JTextField();
        medrecLbl = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.inactiveCaption);
        setPreferredSize(new java.awt.Dimension(650, 500));
        setLayout(null);

        alrg3Txt.setEditable(false);
        alrg3Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alrg3TxtActionPerformed(evt);
            }
        });
        add(alrg3Txt);
        alrg3Txt.setBounds(306, 189, 190, 23);

        medrecTxt.setEditable(false);
        medrecTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medrecTxtActionPerformed(evt);
            }
        });
        add(medrecTxt);
        medrecTxt.setBounds(306, 60, 190, 23);

        alrg1Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alrg1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        alrg1Lbl.setText("Allergy 1 :");
        add(alrg1Lbl);
        alrg1Lbl.setBounds(194, 101, 90, 23);

        alrg1Txt.setEditable(false);
        alrg1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alrg1TxtActionPerformed(evt);
            }
        });
        add(alrg1Txt);
        alrg1Txt.setBounds(306, 103, 190, 23);

        alrg2Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alrg2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        alrg2Lbl.setText("Allergy 2 :");
        add(alrg2Lbl);
        alrg2Lbl.setBounds(204, 144, 80, 23);

        medLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        medLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medLbl.setText("Medical Record Information");
        add(medLbl);
        medLbl.setBounds(35, 11, 580, 29);

        alrg3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alrg3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        alrg3.setText("Allergy 3 :");
        add(alrg3);
        alrg3.setBounds(146, 187, 142, 23);

        alrg2Txt.setEditable(false);
        alrg2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alrg2TxtActionPerformed(evt);
            }
        });
        add(alrg2Txt);
        alrg2Txt.setBounds(306, 146, 190, 23);

        medrecLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        medrecLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medrecLbl.setText("Medical Record Number :");
        add(medrecLbl);
        medrecLbl.setBounds(113, 58, 170, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void medrecTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medrecTxtActionPerformed
        // TODO add your handling code here:
        medrecTxt.setEditable(false);
    }//GEN-LAST:event_medrecTxtActionPerformed

    private void alrg1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alrg1TxtActionPerformed
        // TODO add your handling code here:
        alrg1Txt.setEditable(false);
    }//GEN-LAST:event_alrg1TxtActionPerformed

    private void alrg2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alrg2TxtActionPerformed
        // TODO add your handling code here:
        alrg2Txt.setEditable(false);
    }//GEN-LAST:event_alrg2TxtActionPerformed

    private void alrg3TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alrg3TxtActionPerformed
        // TODO add your handling code here:
        alrg3Txt.setEditable(false);
    }//GEN-LAST:event_alrg3TxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alrg1Lbl;
    private javax.swing.JTextField alrg1Txt;
    private javax.swing.JLabel alrg2Lbl;
    private javax.swing.JTextField alrg2Txt;
    private javax.swing.JLabel alrg3;
    private javax.swing.JTextField alrg3Txt;
    private javax.swing.JLabel medLbl;
    private javax.swing.JLabel medrecLbl;
    private javax.swing.JTextField medrecTxt;
    // End of variables declaration//GEN-END:variables

    private void displayperson() {
        
        medrecTxt.setText(person.getM_rcrdnum());
        alrg1Txt.setText(person.getAlrg_1());
        alrg2Txt.setText(person.getAlrg_2());
        alrg3Txt.setText(person.getAlrg_3());
    }
}
