/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.Person;

/**
 *
 * @author ameya
 */
public class ViewDemoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDemoJPanel
     */
    
    
    Person person;
    public ViewDemoJPanel(Person person) {
        initComponents();
        this.person = person;
        displayperson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wgtTxt = new javax.swing.JTextField();
        ssnTxt = new javax.swing.JTextField();
        fnameLbl = new javax.swing.JLabel();
        dobTxt = new javax.swing.JTextField();
        lnameLbl = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        dobLbl = new javax.swing.JLabel();
        fnameTxt = new javax.swing.JTextField();
        ageLbl = new javax.swing.JLabel();
        lnameTxt = new javax.swing.JTextField();
        hgtLbl = new javax.swing.JLabel();
        wgtLbl = new javax.swing.JLabel();
        ssnLbl = new javax.swing.JLabel();
        hgtTxt = new javax.swing.JTextField();
        demoLbl = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.inactiveCaption);
        setPreferredSize(new java.awt.Dimension(650, 500));

        wgtTxt.setEditable(false);
        wgtTxt.setPreferredSize(new java.awt.Dimension(7, 25));
        wgtTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wgtTxtActionPerformed(evt);
            }
        });

        ssnTxt.setEditable(false);
        ssnTxt.setPreferredSize(new java.awt.Dimension(7, 25));
        ssnTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnTxtActionPerformed(evt);
            }
        });

        fnameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fnameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fnameLbl.setText("First Name :");

        dobTxt.setEditable(false);
        dobTxt.setPreferredSize(new java.awt.Dimension(7, 25));
        dobTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTxtActionPerformed(evt);
            }
        });

        lnameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lnameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lnameLbl.setText("Last Name :");

        ageTxt.setEditable(false);
        ageTxt.setPreferredSize(new java.awt.Dimension(7, 25));
        ageTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtActionPerformed(evt);
            }
        });

        dobLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dobLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dobLbl.setText("Date of birth :");

        fnameTxt.setEditable(false);
        fnameTxt.setPreferredSize(new java.awt.Dimension(7, 25));
        fnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTxtActionPerformed(evt);
            }
        });

        ageLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ageLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ageLbl.setText("Age :");

        lnameTxt.setEditable(false);
        lnameTxt.setPreferredSize(new java.awt.Dimension(7, 25));
        lnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameTxtActionPerformed(evt);
            }
        });

        hgtLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hgtLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hgtLbl.setText("Height :");

        wgtLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wgtLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        wgtLbl.setText("Weight :");

        ssnLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ssnLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ssnLbl.setText("SSN :");

        hgtTxt.setEditable(false);
        hgtTxt.setPreferredSize(new java.awt.Dimension(7, 25));
        hgtTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hgtTxtActionPerformed(evt);
            }
        });

        demoLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        demoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        demoLbl.setText("Demographic Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(demoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(fnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(lnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(dobLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(ageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(hgtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hgtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(wgtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wgtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(ssnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ssnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(demoLbl)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hgtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hgtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wgtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wgtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ssnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ageTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtActionPerformed
        // TODO add your handling code here:
        ageTxt.setEditable(false);
    }//GEN-LAST:event_ageTxtActionPerformed

    private void dobTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTxtActionPerformed
        // TODO add your handling code here:
        dobTxt.setEditable(false);
    }//GEN-LAST:event_dobTxtActionPerformed

    private void hgtTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hgtTxtActionPerformed
        // TODO add your handling code here:
        hgtTxt.setEditable(false);
    }//GEN-LAST:event_hgtTxtActionPerformed

    private void ssnTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnTxtActionPerformed
        // TODO add your handling code here:
        ssnTxt.setEditable(false);
    }//GEN-LAST:event_ssnTxtActionPerformed

    private void wgtTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wgtTxtActionPerformed
        // TODO add your handling code here:
        wgtTxt.setEditable(false);
    }//GEN-LAST:event_wgtTxtActionPerformed

    private void lnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameTxtActionPerformed
        // TODO add your handling code here:
        lnameTxt.setEditable(false);
    }//GEN-LAST:event_lnameTxtActionPerformed

    private void fnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTxtActionPerformed
        // TODO add your handling code here:
        fnameTxt.setEditable(false);
    }//GEN-LAST:event_fnameTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLbl;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JLabel demoLbl;
    private javax.swing.JLabel dobLbl;
    private javax.swing.JTextField dobTxt;
    private javax.swing.JLabel fnameLbl;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JLabel hgtLbl;
    private javax.swing.JTextField hgtTxt;
    private javax.swing.JLabel lnameLbl;
    private javax.swing.JTextField lnameTxt;
    private javax.swing.JLabel ssnLbl;
    private javax.swing.JTextField ssnTxt;
    private javax.swing.JLabel wgtLbl;
    private javax.swing.JTextField wgtTxt;
    // End of variables declaration//GEN-END:variables

    private void displayperson() {
        fnameTxt.setText(person.getF_name());
        lnameTxt.setText(person.getL_name());
        dobTxt.setText(person.getDob());
        ageTxt.setText(person.getAge());
        hgtTxt.setText(person.getHgt());
        wgtTxt.setText(person.getWgt());
        ssnTxt.setText(person.getSsn());
    }
}
