/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.Person;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author ameya
 */
public class ViewLicenseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewLicenseJPanel
     */
    Person person;
    public ViewLicenseJPanel(Person person) {
        initComponents();
        this.setSize(2000, 2000);
        this.person = person;
        displayperson();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bldtypeLbl = new javax.swing.JLabel();
        expdtTxt = new javax.swing.JTextField();
        lncsLbl = new javax.swing.JLabel();
        bldtypeTxt = new javax.swing.JTextField();
        lncsTxt = new javax.swing.JTextField();
        issuedtLbl = new javax.swing.JLabel();
        issuedtTxt = new javax.swing.JTextField();
        expdtLbl = new javax.swing.JLabel();
        picLbl = new javax.swing.JLabel();
        lcnsLbl = new javax.swing.JLabel();
        imageLbl = new javax.swing.JLabel();
        pathTxt = new javax.swing.JTextField();

        setBackground(java.awt.SystemColor.inactiveCaption);
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        bldtypeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bldtypeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bldtypeLbl.setText("Blood Type :");

        expdtTxt.setEditable(false);
        expdtTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expdtTxtActionPerformed(evt);
            }
        });

        lncsLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lncsLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lncsLbl.setText("License Number :");

        bldtypeTxt.setEditable(false);
        bldtypeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bldtypeTxtActionPerformed(evt);
            }
        });

        lncsTxt.setEditable(false);
        lncsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lncsTxtActionPerformed(evt);
            }
        });

        issuedtLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        issuedtLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        issuedtLbl.setText("Date of Issue :");

        issuedtTxt.setEditable(false);
        issuedtTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedtTxtActionPerformed(evt);
            }
        });

        expdtLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        expdtLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        expdtLbl.setText("Date of Expirate :");

        picLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        picLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        picLbl.setText("Picture :");

        lcnsLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lcnsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcnsLbl.setText("Driver's License Information");

        imageLbl.setPreferredSize(new java.awt.Dimension(200, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(picLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bldtypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(bldtypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(imageLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pathTxt)
                                        .addGap(10, 10, 10))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(expdtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(expdtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(issuedtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(issuedtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lncsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(lncsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lcnsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lcnsLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lncsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lncsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(issuedtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(issuedtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expdtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(expdtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bldtypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bldtypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(picLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pathTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(imageLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(579, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void expdtTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expdtTxtActionPerformed
        // TODO add your handling code here:
        expdtTxt.setEditable(false);
    }//GEN-LAST:event_expdtTxtActionPerformed

    private void lncsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lncsTxtActionPerformed
        // TODO add your handling code here:
        lncsTxt.setEditable(false);
    }//GEN-LAST:event_lncsTxtActionPerformed

    private void issuedtTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedtTxtActionPerformed
        // TODO add your handling code here:
        issuedtTxt.setEditable(false);
    }//GEN-LAST:event_issuedtTxtActionPerformed

    private void bldtypeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bldtypeTxtActionPerformed
        // TODO add your handling code here:
        bldtypeTxt.setEditable(false);
    }//GEN-LAST:event_bldtypeTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bldtypeLbl;
    private javax.swing.JTextField bldtypeTxt;
    private javax.swing.JLabel expdtLbl;
    private javax.swing.JTextField expdtTxt;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JLabel issuedtLbl;
    private javax.swing.JTextField issuedtTxt;
    private javax.swing.JLabel lcnsLbl;
    private javax.swing.JLabel lncsLbl;
    private javax.swing.JTextField lncsTxt;
    private javax.swing.JTextField pathTxt;
    private javax.swing.JLabel picLbl;
    // End of variables declaration//GEN-END:variables

    private void displayperson() {
        
        lncsTxt.setText(person.getLcnsnum());
        issuedtTxt.setText(person.getIss_dt());
        expdtTxt.setText(person.getExp_dt());
        bldtypeTxt.setText(person.getBld_type());
        pathTxt.setText(person.getPicture());
        
        String getImagepath = pathTxt.getText();
        ImageIcon myimage = new ImageIcon(getImagepath);
        imageLbl.setIcon(myimage);
        
    }
}
