/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.Person;

/**
 *
 * @author ameya
 */

public class ViewCheckingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCheckingJPanel
     */
    Person person;
    public ViewCheckingJPanel(Person person) {
        initComponents();
        this.setSize(2000, 2000);
        this.person = person;
        displayperson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkaccbalTxt = new javax.swing.JTextField();
        chkbnknameTxt = new javax.swing.JTextField();
        chkrtngLbl = new javax.swing.JLabel();
        chkrtngTxt = new javax.swing.JTextField();
        chkacctypeTxt = new javax.swing.JTextField();
        chkaccLbl = new javax.swing.JLabel();
        chkacctypeLbl = new javax.swing.JLabel();
        chkLbl = new javax.swing.JLabel();
        chkaccbalLbl = new javax.swing.JLabel();
        chkaccTxt = new javax.swing.JTextField();
        chkbnknameLbl = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.inactiveCaption);
        setPreferredSize(new java.awt.Dimension(650, 500));
        setLayout(null);

        chkaccbalTxt.setEditable(false);
        chkaccbalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkaccbalTxtActionPerformed(evt);
            }
        });
        add(chkaccbalTxt);
        chkaccbalTxt.setBounds(293, 189, 190, 23);

        chkbnknameTxt.setEditable(false);
        chkbnknameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbnknameTxtActionPerformed(evt);
            }
        });
        add(chkbnknameTxt);
        chkbnknameTxt.setBounds(293, 60, 190, 23);

        chkrtngLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkrtngLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chkrtngLbl.setText("Routing Number :");
        add(chkrtngLbl);
        chkrtngLbl.setBounds(152, 101, 120, 23);

        chkrtngTxt.setEditable(false);
        chkrtngTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkrtngTxtActionPerformed(evt);
            }
        });
        add(chkrtngTxt);
        chkrtngTxt.setBounds(293, 103, 190, 23);

        chkacctypeTxt.setEditable(false);
        chkacctypeTxt.setText("Checking");
        chkacctypeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkacctypeTxtActionPerformed(evt);
            }
        });
        add(chkacctypeTxt);
        chkacctypeTxt.setBounds(293, 232, 190, 23);

        chkaccLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkaccLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chkaccLbl.setText("Checking Account Number :");
        add(chkaccLbl);
        chkaccLbl.setBounds(92, 144, 180, 23);

        chkacctypeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkacctypeLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chkacctypeLbl.setText("Account Type :");
        add(chkacctypeLbl);
        chkacctypeLbl.setBounds(155, 230, 120, 23);

        chkLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        chkLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chkLbl.setText("Checking Account Information");
        add(chkLbl);
        chkLbl.setBounds(10, 11, 630, 29);

        chkaccbalLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkaccbalLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chkaccbalLbl.setText("Account Balance :");
        add(chkaccbalLbl);
        chkaccbalLbl.setBounds(133, 187, 142, 23);

        chkaccTxt.setEditable(false);
        chkaccTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkaccTxtActionPerformed(evt);
            }
        });
        add(chkaccTxt);
        chkaccTxt.setBounds(293, 146, 190, 23);

        chkbnknameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkbnknameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chkbnknameLbl.setText("Bank Name :");
        add(chkbnknameLbl);
        chkbnknameLbl.setBounds(171, 58, 100, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void chkbnknameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbnknameTxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_chkbnknameTxtActionPerformed

    private void chkrtngTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkrtngTxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_chkrtngTxtActionPerformed

    private void chkaccTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkaccTxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_chkaccTxtActionPerformed

    private void chkacctypeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkacctypeTxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_chkacctypeTxtActionPerformed

    private void chkaccbalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkaccbalTxtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_chkaccbalTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chkLbl;
    private javax.swing.JLabel chkaccLbl;
    private javax.swing.JTextField chkaccTxt;
    private javax.swing.JLabel chkaccbalLbl;
    private javax.swing.JTextField chkaccbalTxt;
    private javax.swing.JLabel chkacctypeLbl;
    private javax.swing.JTextField chkacctypeTxt;
    private javax.swing.JLabel chkbnknameLbl;
    private javax.swing.JTextField chkbnknameTxt;
    private javax.swing.JLabel chkrtngLbl;
    private javax.swing.JTextField chkrtngTxt;
    // End of variables declaration//GEN-END:variables

    private void displayperson() {
        chkbnknameTxt.setText(person.getChk_name());
        chkrtngTxt.setText(person.getChk__rnum());
        chkaccTxt.setText(person.getChk__accnum());
        chkaccbalTxt.setText(person.getChk__accbal());
        chkacctypeTxt.setText(person.getChk__acctype());
    }
}
