/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.Person;

/**
 *
 * @author ameya
 */
public class ViewAddrJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAddrJPanel
     */
    Person person;
    public ViewAddrJPanel(Person person) {
        initComponents();
        this.setSize(2000, 2000);
        this.person = person;
        displayPerson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        straddrLbl = new javax.swing.JLabel();
        zipTxt = new javax.swing.JTextField();
        cityLbl = new javax.swing.JLabel();
        stateLbl = new javax.swing.JLabel();
        zipLbl = new javax.swing.JLabel();
        straddrTxt = new javax.swing.JTextField();
        cityTxt = new javax.swing.JTextField();
        addrLbl = new javax.swing.JLabel();
        stateTxt = new javax.swing.JTextField();

        setBackground(java.awt.SystemColor.inactiveCaption);
        setPreferredSize(new java.awt.Dimension(650, 500));
        setLayout(null);

        straddrLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        straddrLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        straddrLbl.setText("Street Address :");
        add(straddrLbl);
        straddrLbl.setBounds(119, 58, 150, 23);

        zipTxt.setEditable(false);
        zipTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipTxtActionPerformed(evt);
            }
        });
        add(zipTxt);
        zipTxt.setBounds(290, 189, 190, 23);

        cityLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cityLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cityLbl.setText("City :");
        add(cityLbl);
        cityLbl.setBounds(184, 101, 88, 23);

        stateLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stateLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stateLbl.setText("State :");
        add(stateLbl);
        stateLbl.setBounds(196, 144, 76, 23);

        zipLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zipLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        zipLbl.setText("Zip :");
        add(zipLbl);
        zipLbl.setBounds(209, 187, 63, 23);

        straddrTxt.setEditable(false);
        straddrTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                straddrTxtActionPerformed(evt);
            }
        });
        add(straddrTxt);
        straddrTxt.setBounds(290, 60, 190, 23);

        cityTxt.setEditable(false);
        cityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTxtActionPerformed(evt);
            }
        });
        add(cityTxt);
        cityTxt.setBounds(290, 103, 190, 23);

        addrLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addrLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addrLbl.setText("Address Information");
        add(addrLbl);
        addrLbl.setBounds(10, 11, 630, 29);

        stateTxt.setEditable(false);
        stateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTxtActionPerformed(evt);
            }
        });
        add(stateTxt);
        stateTxt.setBounds(290, 146, 190, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void straddrTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_straddrTxtActionPerformed
        // TODO add your handling code here:
        straddrTxt.setEditable(false);
    }//GEN-LAST:event_straddrTxtActionPerformed

    private void cityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTxtActionPerformed
        // TODO add your handling code here:
        cityTxt.setEditable(false);
    }//GEN-LAST:event_cityTxtActionPerformed

    private void stateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTxtActionPerformed
        // TODO add your handling code here:
        stateTxt.setEditable(false);
        
    }//GEN-LAST:event_stateTxtActionPerformed

    private void zipTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipTxtActionPerformed
        // TODO add your handling code here:
        zipTxt.setEditable(false);
    }//GEN-LAST:event_zipTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addrLbl;
    private javax.swing.JLabel cityLbl;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JLabel stateLbl;
    private javax.swing.JTextField stateTxt;
    private javax.swing.JLabel straddrLbl;
    private javax.swing.JTextField straddrTxt;
    private javax.swing.JLabel zipLbl;
    private javax.swing.JTextField zipTxt;
    // End of variables declaration//GEN-END:variables

    private void displayPerson() {
        
        straddrTxt.setText(person.getStr_addr());
        cityTxt.setText(person.getCity());
        stateTxt.setText(person.getState());
        zipTxt.setText(person.getZip());
        
    }
}
